= Qprompt

== Introduction
This project provides a Python 2.7/3.x library that allows the user to quickly create CLI prompts for user input. The main features are the following:

  - Simple multi-entry menus.
  - Prompt for yes/no response.
  - Prompt for integer response.
  - Prompt for float response.
  - Optional default value.
  - Optional validity check.
  - Should work on any platform without additional dependencies.

== Status
Currently, this project is in the **development release** stage. While this project is suitable for use, please note that there may be incompatibilities in new releases.

== Requirements
Qprompt should run on any Python 2.7/3.x interpreter without additional dependencies.

== Installation
Qprompt can be installed with pip using the following command: `pip install qprompt`

Additional, Qprompt can be installed from source by running: `python setup.py install`

== Usage
The following is an example of basic input usage:

    num = qprompt.ask_int("Enter a multiple of 3", vld=lambda x: x > 0)
    if qprompt.ask_yesno("Show number?", dft=True):
        print(num)

The following is an example of basic menu usage:

    menu = qprompt.Menu()
    menu.add("p", "Previous")
    menu.add("n", "Next")
    menu.add("e", "Exit")
    choice = menu.show()

At any prompt, the user can enter the `?` character to show valid entries:

    >>> qprompt.ask_yesno()
    [?] Proceed?: ?
    ['N', 'NO', 'Y', 'YES', 'n', 'no', 'y', 'yes']

Check out the following additional examples of Qprompt; more can be found https://github.com/jeffrimko/Qprompt/tree/master/examples[here]:

  - https://github.com/jeffrimko/Qprompt/blob/master/examples/ask_1.py[examples/ask_1.py] - Basic info prompting.
  - https://github.com/jeffrimko/Qprompt/blob/master/examples/menu_1.py[examples/menu_1.py] - Basic menu usage.
  - https://github.com/jeffrimko/Qprompt/blob/master/examples/display_1.py[examples/display_1.py] - Basic display functions.
  - https://github.com/jeffrimko/Qprompt/blob/master/examples/status_1.py[examples/status_1.py] - Basic status function usage.

== Documentation
The full documentation for this project can be found http://qprompt.readthedocs.io/en/latest/[here on Read the Docs].

== Similar
The following projects are similar and may be worth checking out:

  - https://github.com/Sleft/cliask[cliask]
  - https://github.com/aventurella/promptly[Promptly]
  - https://github.com/magmax/python-inquirer[python-inquirer]
  - https://github.com/sfischer13/python-prompt[python-prompt]
  - https://github.com/tylerdave/prompter[prompter]
